import { v4 } from 'uuid'
import { Status } from '../../../../../../enums/status'
import { Contact } from '../../../../../../interfaces/contact'

const dummyContacts: Contact[] = [
    {
        firstname: 'Kierra',
        lastname: 'Press',
        lastMessageSeen: true,
        lastMessage: 'Did you see the new movie of sdakjnf kjdsaf dskaj fkjdsa fkjdsa fkjdsa f',
        lastMessageDateNumber: Date.now(),
        lastMessageFromId: v4(),
        status: Status.working,
    },
    {
        firstname: 'Kierra',
        lastname: 'Press',
        lastMessageSeen: false,
        lastMessage: 'Did you see the new movie of',
        lastMessageDateNumber: Date.now(),
        lastMessageFromId: v4(),

        status: Status.working,
    },
    {
        firstname: 'Kierra',
        lastname: 'Press',
        lastMessageSeen: true,
        lastMessage: 'Did you see the new movie of',
        lastMessageDateNumber: Date.now(),
        lastMessageFromId: v4(),
        status: Status.available,
    },
    {
        firstname: 'Kierra',
        lastname: 'Press',
        lastMessageSeen: false,
        lastMessage: 'Did you see the new movie of',
        lastMessageDateNumber: Date.now(),
        lastMessageFromId: v4(),
        status: Status.unavailable,
    },
    {
        firstname: 'Kierra',
        lastname: 'Press',
        lastMessageSeen: false,
        lastMessage: 'Did you see the new movie of',
        lastMessageDateNumber: Date.now(),
        lastMessageFromId: v4(),
        status: Status.unavailable,
    },
    {
        firstname: 'Kierra',
        lastname: 'Press',
        lastMessageSeen: false,
        lastMessage: 'Did you see the new movie of',
        lastMessageDateNumber: Date.now(),
        lastMessageFromId: v4(),
        status: Status.unavailable,
    },
    // {
    //     firstname: 'Kierra',
    //     lastname: 'Press',
    //     lastMessageSeen: false,
    //     lastMessage: 'Did you see the new movie of',
    //     lastMessageDateNumber: Date.now(),
    //     lastMessageFromId: v4(),
    //     status: Status.unavailable,
    // },
    // {
    //     firstname: 'Kierra',
    //     lastname: 'Press',
    //     lastMessageSeen: false,
    //     lastMessage: 'Did you see the new movie of',
    //     lastMessageDateNumber: Date.now(),
    //     lastMessageFromId: v4(),
    //     status: Status.unavailable,
    // },
    // {
    //     firstname: 'Kierra',
    //     lastname: 'Press',
    //     lastMessageSeen: false,
    //     lastMessage: 'Did you see the new movie of',
    //     lastMessageDateNumber: Date.now(),
    //     lastMessageFromId: v4(),
    //     status: Status.unavailable,
    // },
    // {
    //     firstname: 'Kierra',
    //     lastname: 'Press',
    //     lastMessageSeen: false,
    //     lastMessage: 'Did you see the new movie of',
    //     lastMessageDateNumber: Date.now(),
    //     lastMessageFromId: v4(),
    //     status: Status.unavailable,
    // },
    {
        firstname: 'Last',
        lastname: 'Person',
        lastMessageSeen: false,
        lastMessage: 'Did you see the new movie of',
        lastMessageDateNumber: Date.now(),
        lastMessageFromId: v4(),
        status: Status.unavailable,
    },
]
export { dummyContacts }
